version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    profiles:
      - prod
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat_app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"

volumes:
  postgres_data:
