version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - weather_app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - weather_app_network

volumes:
  postgres_data:

networks:
  weather_app_network:
    driver: bridge
